config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => 'users/omniauth_callbacks'}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  root 'welcome#index'

  get 'sites/privacy_policy'
  get 'sites/terms_of_service'
  get 'sites/faq'
  get 'sites/contact_us'
  post 'sites/contact_us/create'

  resources :courses, :schools, :users, :notes, :course_instances, :tutor_ads, :groups, :ratings, :messages
  resources :course_instances do 
  	resources :notes
  end

  resources :notes do
    resources :ratings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_instances
	has_many :groups
	belongs_to :school
	has_and_belongs_to_many :users

	DEPTS =  ['Arts', 'Business', 'Education', 'Applied Science (Psychology)', 'Architectural Technology', 
		'Biological Science', 'Biomedical Science', 'Commerce', 'Communications', 'Creative Arts', 
		'Criminology', 'Design', 'Engineering', 'Forensic Science', 'Health Science', 'Information Systems', 
		'Computer Science', 'Law', 'Nursing', 'Medicine', 'Psychology', 'Teaching']
	validates :department, inclusion: {in: DEPTS}

	def self.DEPTS
		DEPTS
	end
end

app/models/course_instance.rb
class CourseInstance < ApplicationRecord
	has_many :notes
	belongs_to :course
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :messages
	has_and_belongs_to_many :users
	belongs_to :course
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	belongs_to :course_instance
	has_many :ratings
	has_one_attached :file
	include PublicActivity::Model
	tracked

	def ave_rating
		size = 0
		sum = 0
		self.ratings.each do |rating|
			size = size + 1
			sum = sum + rating.score
		end
		if (size ==0)
			return '-'
		end 

		return (sum /size).round(1)

	end

end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :note
	belongs_to :user
end

app/models/school.rb
class School < ApplicationRecord
	has_many :courses
end

app/models/student_group.rb
class StudentGroup < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/tutor_ad.rb
class TutorAd < ApplicationRecord
  belongs_to:user
  enum ad_type: [:wanted, :offering]


  include PgSearch::Model
  pg_search_scope :search, :against => [:title,:description]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  has_many :groups
  has_many :messages
  has_many :tutor_ads
  has_many :ratings
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]


  def self.from_omniauth(auth)
  	# try to find existing user by provider and uid
  	# 	otherwise, create
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def index
  	@notes = Note.all
  end

  def create
  	@course_instance = CourseInstance.find(params[:course_instance_id])
  	@note = @course_instance.notes.new(note_params)
    @note.file.attach(params[:note][:file])
  	@note.user = User.find_by(id:current_user.id)
  	@note.save
  	redirect_to course_instance_path(@course_instance)
  end

  def destroy
    @note = Note.find(params[:id])
  	#@course_instance = CourseInstance.find(params[:course_instance_id])
  	#@note = @course_instance.notes.find(params[:id])
    @course_instance = @note.course_instance
  	@note.destroy
  	redirect_to course_instance_path(@course_instance)
  end

  def show
    @note = Note.find(params[:id])
    #@course_instance = CourseInstance.find(params[:course_instance_id])
    #@note = @course_instance.notes.find(params[:id])
    @course_instance = @note.course_instance
  end


  private
  	def note_params
  		params.require(:note).permit(:title, :body, :file)
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tutor_ads_helper.rb
module TutorAdsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/notes/index.html.erb
<h1>All Notes</h1>

<table class = "table">
  <tr>
    <th>Title</th>
    <th>Body</th>
    <th>Student</th>
    <th>Course</th>
    <th>Semester</th>
  </tr>
 
  <% @notes.each do |note| %>
    <tr>
      <td><%= note.title %></td>
      <td><%= note.body %></td>
      <td><%= "#{note.user.first_name} #{note.user.last_name}" %></td>
      <td><%= note.course_instance.course.course_name %></td>
      <td><%= "#{note.course_instance.semester} #{note.course_instance.year}" %></td>
    </tr>
  <% end %>
</table>

app/views/notes/show.html.erb
<header class="masthead">
    <div class="container">
      <div class="row h-100" align="center" style="padding-top: 90px; ">
            <div class="col mb-3 " align="center" >
<h1><%= @course_instance.course.course_code %> - <%= @course_instance.course.course_name %></h1>

<h2><%= @note.title %> </h2>

<p> <%= @note.body %> </p>

<% if @note.file.attached? %>
	<% if @note.file.filename.extension == "pdf" %>
		<iframe width = "90%" height= "700" src= <%= rails_blob_path(@note.file, disposition: "file") %>></iframe>
	<% else %>
		<p> Download <%= link_to @note.file.filename.to_s, rails_blob_path(@note.file, disposition: "file") %> </p>
	<% end %>
<% end %>

<p><%= link_to "return", course_instance_path(@course_instance), :class=>"btn btn-primary" %></p>

<p><%= link_to "add review", new_note_rating_path(@note), :class=>"btn btn-primary"%></p>

<p><%= link_to "view all reviews", note_ratings_path(@note), :class=>"btn btn-primary"%></p>

</div>
</div>

        <div class="header-content mx-auto">
      </div>
      </div>
    </header>

app/views/public_activity/note/_create.html.erb
<li class="list-group-item">
      <% if a.trackable %>
              <%= link_to a.trackable.title, a.trackable%>
      <% else %>
	    A posting that is currently deleted was added.
      <% end %>
</li>

app/views/public_activity/note/_destroyed.html.erb
<li class="list-group-item">
	  An aticle was deleted.
</li>

app/views/public_activity/note/_update.html.erb
<li class="list-group-item">
	<% if.trackable %>
	   <%= a.trackable.title %> was edited.
	<% else %>
	    A posting that is currently deleted was edited.
	<% end %>
</li>