config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => 'users/omniauth_callbacks'}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  root 'welcome#index'

  get 'sites/privacy_policy'
  get 'sites/terms_of_service'
  get 'sites/faq'
  get 'sites/contact_us'
  post 'sites/contact_us/create'

  resources :courses, :schools, :users, :notes, :course_instances, :tutor_ads, :groups, :ratings, :messages
  resources :course_instances do 
  	resources :notes
  end

  resources :notes do
    resources :ratings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_instances
	has_many :groups
	belongs_to :school
	has_and_belongs_to_many :users

	DEPTS =  ['Arts', 'Business', 'Education', 'Applied Science (Psychology)', 'Architectural Technology', 
		'Biological Science', 'Biomedical Science', 'Commerce', 'Communications', 'Creative Arts', 
		'Criminology', 'Design', 'Engineering', 'Forensic Science', 'Health Science', 'Information Systems', 
		'Computer Science', 'Law', 'Nursing', 'Medicine', 'Psychology', 'Teaching']
	validates :department, inclusion: {in: DEPTS}

	def self.DEPTS
		DEPTS
	end
end

app/models/course_instance.rb
class CourseInstance < ApplicationRecord
	has_many :notes
	belongs_to :course
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :messages
	has_and_belongs_to_many :users
	belongs_to :course
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	belongs_to :course_instance
	has_many :ratings
	has_one_attached :file
	include PublicActivity::Model
	tracked

	def ave_rating
		size = 0
		sum = 0
		self.ratings.each do |rating|
			size = size + 1
			sum = sum + rating.score
		end
		if (size ==0)
			return '-'
		end 

		return (sum /size).round(1)

	end

end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :note
	belongs_to :user
end

app/models/school.rb
class School < ApplicationRecord
	has_many :courses
end

app/models/student_group.rb
class StudentGroup < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/tutor_ad.rb
class TutorAd < ApplicationRecord
  belongs_to:user
  enum ad_type: [:wanted, :offering]


  include PgSearch::Model
  pg_search_scope :search, :against => [:title,:description]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  has_many :groups
  has_many :messages
  has_many :tutor_ads
  has_many :ratings
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]


  def self.from_omniauth(auth)
  	# try to find existing user by provider and uid
  	# 	otherwise, create
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
  end
  def index
    @groups = Group.all
  end
  def create
  	@group = Group.new(group_params)
 
  	@group.save
  	redirect_to @group
  end
  def update
    # currently called when user clicks join group
    group = Group.find(params[:id])
    group.users << current_user
    group.save
    redirect_to group_path(group)
  end
  def show
    @group = Group.find(params[:id])
    @messages = Message.where("group_id = ? ", params[:id])
  end

  private
    def group_params
      params.require(:group).permit(:name, :course_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tutor_ads_helper.rb
module TutorAdsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/index.html.erb
<header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-lg-7 my-auto">
          <div class="header-content mx-auto">
            <div class="container">
              <div class="row">
              <div class="col">
        <h1>All Groups</h1>
        <table class="table table-light table-striped" id="myTable">
          <%= link_to '<button type="button" class="btn btn-primary">New Group</button>'.html_safe, new_group_path() %>
          <thead class="thead-dark">
            <tr>
              <th class="text-center" data-sortable="true">Group Name</th>
              <th class="text-center" data-sortable="true">Course Code</th>
            </tr>
          </thead>
          <tbody>
              <% @groups.each do |group| %>            
              <tr>
              <td class="text-center text-dark" style="vertical-align: middle;"><%= link_to group.name, group_path(group) %></td>
              <td class="text-center text-dark" style="vertical-align: middle; text-transform: uppercase;"><%= group.course.course_code%></td>
            </tr>
          <%end%>
          </tbody>
        </table>

          </div>
         </div>
        </div>
      </div>
      </div>
        </div>
      </div>
    </div>
</header>



<script>
$(document).ready(function(){
    $('#myTable').dataTable({
        "bLengthChange": false,
        "iDisplayLength": 13,
        "bFilter": false
    });
});

//window.onload = function() {
  //  if (window.jQuery) {  
        // jQuery is loaded  
    //    alert("Yeah!");
    //} else {
        // jQuery is not loaded
      //  alert("Doesn't Work");
//    }
//}

</script>

app/views/groups/new.html.erb
<header class="masthead">
    <div class="container">
      <div class="row h-100" align="center" style="padding-top: 90px; ">
            <div class="col mb-3 " align="center" >
              <div class="card" id = "course-instance-form">
                <div class="card-body text-dark">
<h1>New Group</h1>


<%= form_with scope: :group, url: groups_path, local: true do |form| %>
    <% if current_user.courses.length == 0 %>
    <p>You must be registered in a course to sign up to a group!</p>
    <%= link_to "Add a course", schools_path %>
  <% else %>
    <p>
      <%= form.label :name%><br>
      <%= form.text_field :name%>
    </p>

    <p>
      <%= form.label :course %> <br>
      <%= form.collection_select(:course_id, current_user.courses, :id, :course_code) %>
    </p>
   
    <p>
      <%= form.submit 'Add',:class => 'btn btn-primary' %>
    </p>
  <% end %>
<% end %>
</div>
</div>
</div>
</div>

        <div class="header-content mx-auto">
      </div>
      </div>
    </header>

app/views/groups/show.html.erb
<header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col ">
          
<h1 class="text-center" style="padding-top: 30px;"><%= @group.name %>-<%= @group.course.course_code %></h1>
<div class="row" style="padding-top: 30px;">
<div class="col">
<h3>Users </h3>
<% if @group.users.length == 0 %> 
	<h3> No users! </h3>
<% else %>
	<table class="table table-light table-striped" id="myTable">
          <thead class="thead-dark">
            <tr>
              <th class="text-center" data-sortable="true">Users</th>
              <th class="text-center" data-sortable="false"></th>
            </tr>
          </thead>
          <tbody>     
          	<% @group.users.each do |usr| %>
              <tr>
              <td class="text-center text-dark" style="vertical-align: middle;"><%= "#{usr.first_name} #{usr.last_name}" %></td>
              <td class="text-center text-dark" style="vertical-align: middle; text-transform: uppercase;"></td>
            </tr>
          <%end%>
          </tbody>
        </table>
<% end %>

<% if not @group.users.include? current_user %>
	<%= link_to 'Join Group', group_path(@group), method: :patch, :class=>"btn btn-primary" %>
<% end %>
</div>
<div class="col-1"></div>
<div class="col" >
<h3> Message Board </h3>
<% if @messages.length == 0 %> 
	<p> No messages! </p>
<% else %>
<ul class="list-group" id="overflow" style="padding-top: 7px;">
	<% @messages.each do |msg| %>
		<li class="list-group-item text-dark"> 
			<%= "#{msg.user.first_name} #{msg.user.last_name}" %>:
		    <strong> <%= msg.title %> </strong>
		    <%= msg.text %>
		    <%= msg.created_at %>		
		</li>
	<% end %>
	</ul>
<% end %>


<% if @group.users.include? current_user %>
	<h3> Add Message </h3>
	<div class="card" style="width: 300px;">
	<div class="card-body" >
	<%= form_with scope: :message, url: messages_path, local: true do |form| %>
	   <div class="form-group text-dark">
	      <%= form.label :title%><br>
	      <%= form.text_field :title%>
	   </div>
	    <div class="form-group text-dark">
	      <%= form.label :text %> <br>
	      <%= form.text_field :text %>
	    </div>
	   	
	   	<%= form.hidden_field :user_id, :value => current_user.id %>
	   	<%= form.hidden_field :group_id, :value => @group.id %>

	    <div class="form-group text-dark">
	    	<%= form.submit "Post", class: "btn btn-primary" %>
	    </div>

	<% end %>
<% end %>
</div>
</div>
</div>
</div>
      </div>
        </div>
      </div>
    </div>
    <div class="header-content mx-auto">
</header>


<script>
$(document).ready(function(){
    $('#myTable').dataTable({
        "bLengthChange": false,
        "iDisplayLength": 13,
        "bFilter": false
    });
});

//window.onload = function() {
  //  if (window.jQuery) {  
        // jQuery is loaded  
    //    alert("Yeah!");
    //} else {
        // jQuery is not loaded
      //  alert("Doesn't Work");
//    }
//}

</script>