config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => 'users/omniauth_callbacks'}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  root 'welcome#index'

  get 'sites/privacy_policy'
  get 'sites/terms_of_service'
  get 'sites/faq'
  get 'sites/contact_us'
  post 'sites/contact_us/create'

  resources :courses, :schools, :users, :notes, :course_instances, :tutor_ads, :groups, :ratings, :messages
  resources :course_instances do 
  	resources :notes
  end

  resources :notes do
    resources :ratings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_instances
	has_many :groups
	belongs_to :school
	has_and_belongs_to_many :users

	DEPTS =  ['Arts', 'Business', 'Education', 'Applied Science (Psychology)', 'Architectural Technology', 
		'Biological Science', 'Biomedical Science', 'Commerce', 'Communications', 'Creative Arts', 
		'Criminology', 'Design', 'Engineering', 'Forensic Science', 'Health Science', 'Information Systems', 
		'Computer Science', 'Law', 'Nursing', 'Medicine', 'Psychology', 'Teaching']
	validates :department, inclusion: {in: DEPTS}

	def self.DEPTS
		DEPTS
	end
end

app/models/course_instance.rb
class CourseInstance < ApplicationRecord
	has_many :notes
	belongs_to :course
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :messages
	has_and_belongs_to_many :users
	belongs_to :course
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	belongs_to :course_instance
	has_many :ratings
	has_one_attached :file
	include PublicActivity::Model
	tracked

	def ave_rating
		size = 0
		sum = 0
		self.ratings.each do |rating|
			size = size + 1
			sum = sum + rating.score
		end
		if (size ==0)
			return '-'
		end 

		return (sum /size).round(1)

	end

end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :note
	belongs_to :user
end

app/models/school.rb
class School < ApplicationRecord
	has_many :courses
end

app/models/student_group.rb
class StudentGroup < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/tutor_ad.rb
class TutorAd < ApplicationRecord
  belongs_to:user
  enum ad_type: [:wanted, :offering]


  include PgSearch::Model
  pg_search_scope :search, :against => [:title,:description]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  has_many :groups
  has_many :messages
  has_many :tutor_ads
  has_many :ratings
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]


  def self.from_omniauth(auth)
  	# try to find existing user by provider and uid
  	# 	otherwise, create
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def google_oauth2
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in @user, :event => :authentication #this will throw if @user is not activated
    else
      session["devise.google_data"] = request.env["omniauth.auth"]
    end
    redirect_to root_path
  end


  def failure
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@users = User.all
  end

  def show
    @user = User.find(params[:id])
    @notes_count = Note.where("user_id = ? ", params[:id]).length
    
    if current_user.id != @user.id
      redirect_to root_path 
    end
  end

  def edit
  	@user = User.find(params[:id])
    
    if current_user.id != @user.id
      redirect_to root_path 
    end
  end

  def update
	  @user = User.find(params[:id])
    
    if current_user.id != @user.id
      redirect_to root_path 
      return
    end
    
    if (params[:add_course])
      course = Course.find(params[:add_course])

      @user.courses << course
      @user.save

      @school = course.school
      render "schools/show"
	  elsif (params[:rm_course])
      course = Course.find(params[:rm_course])

      @user.courses.delete(course)
      @user.save
      redirect_to root_path
    else  
	    if @user.update(user_params)
        if current_user.sign_in_count == 1 
          redirect_to root_path
        else
	       redirect_to @user
        end
  	  else
	      render 'edit'
      end
    
    end
  end

  private
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tutor_ads_helper.rb
module TutorAdsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/users/edit.html.erb
<header class="masthead">
    <div class="container h-100">
      <div class="row flex-lg-nowrap text-dark">
        <div class="col">
          <div class="row" style="padding-top: 40px; ">
            <div class="col mb-3" >
              <div class="card" >
          <div class="card-body" style="padding-top: 20px; ">
            <div class="e-profile">
              <div class="row">
                 <div class="col-12 col-sm-auto mb-3">
                  <div class="mx-auto" style="width: 140px;">
                    <div class="d-flex justify-content-center align-items-center rounded outter" style="height: 140px; ">
                      <% source = "general/defaultProfile.jpg" %>
                      <%= image_tag(source, :class=>"image-circle") %>
                    </div>
                  </div>
                </div>
                <div class="col d-flex flex-column flex-sm-row justify-content-between mb-3" style="padding-left:60px;">
                  <div class="text-center text-sm-left mb-2 mb-sm-0">
                    <h4 class="pt-sm-2 pb-1 mb-0 text-nowrap"><%= @user.first_name %> <%= @user.last_name %></h4>
                    <small><%= @user.email %></small>
                    <div class="mt-2">
                      <button class="btn btn-primary" type="button">
                        <i class="fa fa-fw fa-camera"></i>
                        <span>Change Photo</span>
                      </button>
                    </div>
                  </div>
                  <div class="text-center text-sm-right">
                    <span class="badge badge-secondary">administrator</span>
                    <div class="text-muted"><small>Joined <%= current_user.created_at.to_date %></small></div>
                  </div>
                </div>
              </div>
              <ul class="nav nav-tabs">
                <li class="nav-item"><a href="" class="active nav-link">Settings</a></li>
              </ul>
              <div class="tab-content pt-3">
                <div class="tab-pane active">
                  <%= form_with(model: @user, url: user_path, method: "patch", local: true, id:"form1") do |form| %>
 
                  <% if @user.errors.any? %>
                    <div id="error_explanation">
                    <h2>
                      <%= pluralize(@user.errors.count, "error") %> prohibited
                      these changes from being saved:
                    </h2>
                    <ul>
                      <% @user.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                      <% end %>
                  </ul>
                </div>
                <% end %> 
        
                  <form class="form" novalidate="">
                    <div class="row">
                      <div class="col">
                        <div class="row">
                          <div class="col">
                            <div class="form-group">
                              <%= form.label :first_name, class: 'text-dark' %><br>
                              <%= form.text_field :first_name, :required => true, class: 'text-dark form-control'%>
                            </div>
                            
                          </div>
                          <div class="col">
                            <div class="form-group">
                              <%= form.label :last_name, class: 'text-dark' %><br>
                              <%= form.text_field :last_name, :required => true, class: 'text-dark form-control'%>
                            </div>
                          </div>
                          <% end %>
                        </div>
                        <%= form_for(resource, as: resource_name, url: session_path(resource_name), id:"form2", html: { method: :put }) do |f| %>
                        <%= render "devise/shared/error_messages", resource: resource %>
                        <div class="row">
                          <div class="col">
                            <div class="form-group">
                              <%= f.label :email, class: 'text-dark'  %>
                              <%= f.email_field :email, autofocus: true, autocomplete: "email", class: 'text-dark form-control', disabled:true, placeholder: current_user.email%>
                            </div>
                            <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
                              <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-12 col-sm-6 mb-3">
                        <div class="mb-2"><b>Change Password</b></div>
                        <div class="row">
                          <div class="col">
                            <div class="form-group">
                              <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
                              <%= f.password_field :current_password, autocomplete: "current-password", placeholder: "••••••", class: 'text-dark form-control', disabled: true %>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                            <div class="form-group">
                              <%= f.label :password %> <i> (leave blank if you don't want to change it)</i><br />
                              <%= f.password_field :password, autocomplete: "new-password", placeholder: "••••••", class: 'text-dark form-control', disabled:true %>
                              <% if @minimum_password_length %>
                                <br />
                                <em><%= @minimum_password_length %> characters minimum</em>
                              <% end %>
                            </div>
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                            <div class="form-group">
                              <%= f.label :password_confirmation %><br />
                              <%= f.password_field :password_confirmation, autocomplete: "new-password", placeholder: "••••••", class: 'text-dark form-control', disabled:true %>
                          </div>
                        </div>
                      </div>
                      <% end %>
                      
                    <div class="row">
                      <div class="col d-flex justify-content-end">
                        <%= link_to '<button class="btn btn-primary" type="button">Change email or password</button>'.html_safe, edit_user_registration_path %> 
                        <input type="button" style="height: 35px; margin-left: 20px;" class="btn btn-primary" value="Save Name Changes" onclick="submitForms()" />
                      </div>
                      
                    </div>
                  </form>

                </div>
                 </div>
            </div>
          </div>
        </div>
      </div>
      
          
         </article>
        </div>
        </div>
        </div>
      </div>
    </div>
</header>

<script type="text/javascript">
  submitForms = function(){
    document.getElementById("form1").submit();
    document.getElementById("form2").submit();
}
</script>

app/views/users/index.html.erb
<h1>All Users</h1>

<table class="table">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.last_name %></td>
      <td><%= user.email %></td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<header class="masthead">
  <div class="container">
  <div class="row login_box">
      <div class="col-md-12 col-xs-12" align="center">
            <div class="line"><h3>USER PROFILE</h3></div>
            
            <% source = "general/defaultProfile.jpg" %>
                
            <div class="outter"><%= image_tag(source, :class=>"image-circle") %></div>  
            <%= link_to '<button style="margin-top: 13px;"class="btn btn-primary" type="button">Edit Profile</button>'.html_safe, edit_user_path %> 
            <h3><%= @user.first_name %>
            <%= @user.last_name %></h3>
            
            <span>Admin</span>

      </div>
        <div class="col-md-6 col-xs-6 follow line" align="center">
            <h3>
                 <%= @notes_count %> <br/> <span>Notes Posted</span>
            </h3>
        </div>
        <div class="col-md-6 col-xs-6 follow line" align="center">
            <h3>
                 <%= current_user.courses.length %> <br/> <span>Enrolled Courses</span>
            </h3>
        </div> 
        <div style="width: 100%;" class="text-center">
        <h5 class="text-center"><strong>Email:</strong> <%= @user.email %></h5>
        </div>      
    </div>
</div>
</header>

         