config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => {:registrations => "registrations", :omniauth_callbacks => 'users/omniauth_callbacks'}
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'welcome/index'

  root 'welcome#index'

  get 'sites/privacy_policy'
  get 'sites/terms_of_service'
  get 'sites/faq'
  get 'sites/contact_us'
  post 'sites/contact_us/create'

  resources :courses, :schools, :users, :notes, :course_instances, :tutor_ads, :groups, :ratings, :messages
  resources :course_instances do 
  	resources :notes
  end

  resources :notes do
    resources :ratings
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_instances
	has_many :groups
	belongs_to :school
	has_and_belongs_to_many :users

	DEPTS =  ['Arts', 'Business', 'Education', 'Applied Science (Psychology)', 'Architectural Technology', 
		'Biological Science', 'Biomedical Science', 'Commerce', 'Communications', 'Creative Arts', 
		'Criminology', 'Design', 'Engineering', 'Forensic Science', 'Health Science', 'Information Systems', 
		'Computer Science', 'Law', 'Nursing', 'Medicine', 'Psychology', 'Teaching']
	validates :department, inclusion: {in: DEPTS}

	def self.DEPTS
		DEPTS
	end
end

app/models/course_instance.rb
class CourseInstance < ApplicationRecord
	has_many :notes
	belongs_to :course
end

app/models/group.rb
class Group < ApplicationRecord
	has_many :messages
	has_and_belongs_to_many :users
	belongs_to :course
end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	belongs_to :course_instance
	has_many :ratings
	has_one_attached :file
	include PublicActivity::Model
	tracked

	def ave_rating
		size = 0
		sum = 0
		self.ratings.each do |rating|
			size = size + 1
			sum = sum + rating.score
		end
		if (size ==0)
			return '-'
		end 

		return (sum /size).round(1)

	end

end

app/models/rating.rb
class Rating < ApplicationRecord
	belongs_to :note
	belongs_to :user
end

app/models/school.rb
class School < ApplicationRecord
	has_many :courses
end

app/models/student_group.rb
class StudentGroup < ApplicationRecord
	belongs_to :group
	belongs_to :user
end

app/models/tutor_ad.rb
class TutorAd < ApplicationRecord
  belongs_to:user
  enum ad_type: [:wanted, :offering]


  include PgSearch::Model
  pg_search_scope :search, :against => [:title,:description]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :notes
  has_many :groups
  has_many :messages
  has_many :tutor_ads
  has_many :ratings
  has_and_belongs_to_many :courses
  has_and_belongs_to_many :groups
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:facebook, :google_oauth2]


  def self.from_omniauth(auth)
  	# try to find existing user by provider and uid
  	# 	otherwise, create
  	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0, 20]
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
    end
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  def index
  	@schools = School.all
  end

  def show
  	@school = School.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper 
  def resource_name
    :user
  end
 
  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/tutor_ads_helper.rb
module TutorAdsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/schools/index.html.erb
<header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col-lg-7 my-auto">
          <div class="header-content mx-auto">
            <div class="container">
              <div class="row">
              <div class="col">
        <h1>All Schools</h1>
        <div class="d-inline-block">
          <h4>School missing?</h4>
        </div>
          <div class="d-inline-block"> 
          <%= link_to '<button type="button" class="btn btn-primary">Let us know.</button>'.html_safe, sites_contact_us_path %>
        </div>
        <table class="table table-light table-striped" id="myTable">
          <thead class="thead-dark">
            <tr>
              <th class="text-center" data-sortable="true">School Name</th>
              <th class="text-center" data-sortable="true">City</th>
            </tr>
          </thead>
          <tbody>
              <% @schools.each do |school| %>            
              <tr>
              <td class="text-center text-dark" style="width: 120px;vertical-align: middle;"><%= link_to school.school_name, school_path(school) %></td>
              <td class="text-center text-dark" style="vertical-align: middle; text-transform: uppercase;"><%= school.city %></td>
            </tr>
          <%end%>
          </tbody>
        </table>

          </div>
         </div>
        </div>
      </div>
      </div>
        </div>
      </div>
    </div>
</header>



<script>
$(document).ready(function(){
    $('#myTable').dataTable({
        "bLengthChange": false,
        "iDisplayLength": 8,
        "bFilter": false
    });
});

//window.onload = function() {
  //  if (window.jQuery) {  
        // jQuery is loaded  
    //    alert("Yeah!");
    //} else {
        // jQuery is not loaded
      //  alert("Doesn't Work");
//    }
//}

</script>

app/views/schools/show.html.erb
<header class="masthead">
    <div class="container h-100">
      <div class="row h-100">
        <div class="col" style="padding-top: 50px;">
          
<h1 class="text-center">
  <strong><%= @school.school_name %></strong>
</h1>

<h2>Courses by Department</h2>

<% course_dept = {} %>
<% count = 0 %>
<% Course.DEPTS.each do |department| %>
  <% course_dept[department] = [] %>
<% end %>
<% @school.courses.each do |course| %>
  <% course_dept[course.department].push(course) %>
<% end %>

<% Course.DEPTS.each do |department| %>
  <% if course_dept[department].length != 0 %>
  <% if count%3 == 0 %>
    <div class="row">
  <% end %>
  <div class="col">
    <h3 class="text-center"> <%= department %></h3>
    <% count = count + 1 %>        
    <% string = "myTable" + count.to_s %>
    <table class="table table-light table-striped" id=<%= string %>>
      <thead class="thead-dark">
      <tr>
        <th class="text-center" data-sortable="true">Course Code</th>
        <th class="text-center" data-sortable="true">Course Name</th>
        <th class="text-center" data-sortable="false"></th>
      </tr>
    </thead>
     
      <% course_dept[department].each do |course| %>
        <tr>
          <td><%= link_to course.course_code, course_path(course) %></td>
          <td><%= course.course_name %></td>
          <% if current_user.courses.include?(course) %>
            <td> <%= link_to "View My Courses", root_path %> </td>
          <% else %>
            <td><%= link_to "Add Course", user_path(current_user, add_course: course.id), method: :patch %></td>
          <% end %>
        </tr>
      <% end %>
    </table>
    <% if count%3 == 0 %>
    </div>
  <% end %>
</div>
  <% end %>
<% end %>

</div>
        </div>
      </div>
    </div>
    <div class="header-content mx-auto">
</header>


<script>
$(document).ready(function(){
  var i = 0;
    while (i <= <%= count %>) {
    $('#myTable'+ i).dataTable({
        "bLengthChange": false,
        "iDisplayLength": 5,
        "bFilter": false
    });
    i++;
  }
});

//window.onload = function() {
  //  if (window.jQuery) {  
        // jQuery is loaded  
    //    alert("Yeah!");
    //} else {
        // jQuery is not loaded
      //  alert("Doesn't Work");
//    }
//}

</script>